/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface EvbButtonBar {
    'justify': 'left' | 'center' | 'right';
  }
  interface EvbButtonBarAttributes extends StencilHTMLAttributes {
    'justify'?: 'left' | 'center' | 'right';
  }

  interface EvbButton {
    'disabled': boolean;
    'ghost': any;
    'href'?: string;
    'type'?: 'submit' | 'button' | 'reset';
  }
  interface EvbButtonAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'ghost'?: any;
    'href'?: string;
    'onEvbBlur'?: (event: CustomEvent<void>) => void;
    'onEvbFocus'?: (event: CustomEvent<void>) => void;
    'type'?: 'submit' | 'button' | 'reset';
  }

  interface EvbCollection {}
  interface EvbCollectionAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EvbButtonBar': Components.EvbButtonBar;
    'EvbButton': Components.EvbButton;
    'EvbCollection': Components.EvbCollection;
  }

  interface StencilIntrinsicElements {
    'evb-button-bar': Components.EvbButtonBarAttributes;
    'evb-button': Components.EvbButtonAttributes;
    'evb-collection': Components.EvbCollectionAttributes;
  }


  interface HTMLEvbButtonBarElement extends Components.EvbButtonBar, HTMLStencilElement {}
  var HTMLEvbButtonBarElement: {
    prototype: HTMLEvbButtonBarElement;
    new (): HTMLEvbButtonBarElement;
  };

  interface HTMLEvbButtonElement extends Components.EvbButton, HTMLStencilElement {}
  var HTMLEvbButtonElement: {
    prototype: HTMLEvbButtonElement;
    new (): HTMLEvbButtonElement;
  };

  interface HTMLEvbCollectionElement extends Components.EvbCollection, HTMLStencilElement {}
  var HTMLEvbCollectionElement: {
    prototype: HTMLEvbCollectionElement;
    new (): HTMLEvbCollectionElement;
  };

  interface HTMLElementTagNameMap {
    'evb-button-bar': HTMLEvbButtonBarElement
    'evb-button': HTMLEvbButtonElement
    'evb-collection': HTMLEvbCollectionElement
  }

  interface ElementTagNameMap {
    'evb-button-bar': HTMLEvbButtonBarElement;
    'evb-button': HTMLEvbButtonElement;
    'evb-collection': HTMLEvbCollectionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
